Fix 149, commit append to the last line
jreybert/vimagit pull request #150
Opened 2017-10-31 15:24 UTC by iaia

ref. #149 

When set commit at the end of default section, append to the last line.

2017-11-05 09:26 UTC, jreybert commented
Just to let you know, I watched your PR the first day, but I did not found time to test it.

Seems quite good to me. I just wonder the `w$` pattern, maybe the pattern `end of file`would be better (i can't remember right now the exact syntax of this pattern).

Thanks for the PR anyway!

2017-11-05 13:23 UTC, iaia commented
Thank you for reviewing.
What you are saying is maybe `$EOF`? I fixed. please review again.

2017-11-06 09:50 UTC, jreybert commented
End of file vim pattern is `\%$` (see `:help %$`). `$EOF` doe snot exists in vim.

2017-11-06 12:33 UTC, jreybert requested changes
you spotted the right codelines to fix the bug, but the fix is wrong.

The usage of `line()` makes no sense here, you don't want to check against the content of the last line (which is certainly `empty line`), because you could have empty line in your commit message. Instead, use the pattern `\%$`, which is regex pattern for end of file.

Others comments are mainly cosmetics, but I would appreciate them too.

2017-11-06 12:33 UTC, jreybert commented on plugin/magit.vim
> +	if ( match(g:magit_default_sections, 'commit')+1 >= len(g:magit_default_sections) )
use intermediate variable to store `match(g:magit_default_sections, 'commit')` result
check if this position is equal to len + 1

2017-11-06 12:33 UTC, jreybert commented on plugin/magit.vim
> +		let commit_position = line("$EOF")
do not use intermediate variable for this, store directly in commit_section_pat_end

use `\%$` pattern, without `line()`

2017-11-06 12:33 UTC, jreybert commented on plugin/magit.vim
> +		let commit_position = g:magit_sections[g:magit_default_sections[match(g:magit_default_sections, 'commit')+1]]
use intermediate variable declared before

keep `^` and `$` here

2017-11-06 13:34 UTC, iaia commented
@jreybert sorry, i am not good at writing vimscript.
I rewrote it. please review again. thank you.

2017-11-06 15:17 UTC, jreybert requested changes
Excellent! Just one last thing and you're good.

2017-11-06 15:17 UTC, jreybert commented on plugin/magit.vim
> +	  let commit_section_pat_end='^'.g:magit_sections[g:magit_default_sections[match(g:magit_default_sections, 'commit')+1]].'$'
Reuse `commit_position` here.

2017-11-06 15:34 UTC, iaia commented on plugin/magit.vim
> +	  let commit_section_pat_end='^'.g:magit_sections[g:magit_default_sections[match(g:magit_default_sections, 'commit')+1]].'$'
I fixed!

2017-11-06 16:16 UTC, jreybert requested changes
Perfect.

I am sorry, two last things I did not noticed the first time:
* remove the file `.development.vim` from your commit
* rename the commit title to something like: "Handle commit set at the end of magit_default_sections", and add "ref #149" (the sign # is important) in the commit body.

2017-11-06 22:40 UTC, iaia commented
oops! sorry, i deleted `.development.vim`. and change commit message.

2017-11-07 13:11 UTC, jreybert approved these changes

2017-11-07 13:12 UTC, merged

2017-11-07 13:13 UTC, jreybert commented
Excellent, thanks for the PR and for all your changes through the review process!

2017-11-07 13:29 UTC, iaia commented
Thanks for the merge!